 
version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
    - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
    - zookeeper
    links:
      - zookeeper:zookeeper
    ports:
    - "9092:9092"
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    
  producer:
    build: ./produce
    depends_on:
    - kafka
    links:
      - kafka:kafka
    environment:
      KAFKA_ADDR: "kafka:9092"
      TOPIC: "my-topic"

  consumer:
    build: ./consume
    depends_on:
    - kafka
    links:
      - kafka:kafka
    environment:
      KAFKA_ADDR: "kafka:9092"
      TOPIC: "my-topic"